[tool.poetry]
name = "mute-profanity"
version = "0.1.0"
description = ""
authors = ["Aaron Smith <aaronsmith1234@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
